version: '3.8'
services:
    llm_tools-core:
        image: llm_tools-core:latest
        container_name: llm_tools-core
        build:
            context: .
            dockerfile: ./docker-images-build/core/Dockerfile

    weaviate:
        image: cr.weaviate.io/semitechnologies/weaviate:latest
        container_name: llm-tools-weaviate
        command:
            - --host
            - 0.0.0.0
            - --port
            - "8080"
            - --scheme
            - http
        volumes:
            - $PWD/resources/db/weaviate:/resources/weaviate
        environment:
            QUERY_DEFAULTS_LIMIT: 25
            AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
            PERSISTENCE_DATA_PATH: "/resources/weaviate"
            DEFAULT_VECTORIZER_MODULE: "none"
            ENABLE_MODULES: ""
            AUTOSCHEMA_ENABLED: "false"
            CLUSTER_HOSTNAME: "node1"
        ports:
            - 8080:8080
            - 50051:50051
        deploy:
            resources:
                limits:
                    cpus: "1"
                    memory: 512M